package pl.edu.pwr.szlagor.masterthesis.linguisticsummary.source.business.service.daySchema;

import static pl.edu.pwr.szlagor.masterthesis.linguisticsummary.source.business.service.activity.SampleActivities.DRESSING_OUT;
import static pl.edu.pwr.szlagor.masterthesis.linguisticsummary.source.business.service.activity.SampleActivities.DRESSING_UP;
import static pl.edu.pwr.szlagor.masterthesis.linguisticsummary.source.business.service.activity.SampleActivities.GOING_AROUND;
import static pl.edu.pwr.szlagor.masterthesis.linguisticsummary.source.business.service.activity.SampleActivities.OUT_IN_GYM;
import static pl.edu.pwr.szlagor.masterthesis.linguisticsummary.source.business.service.activity.SampleActivities.WALK_OUT;
import static pl.edu.pwr.szlagor.masterthesis.linguisticsummary.source.business.service.room.SampleRooms.HALL;
import static pl.edu.pwr.szlagor.masterthesis.linguisticsummary.source.business.service.room.SampleRooms.KITCHEN;
import static pl.edu.pwr.szlagor.masterthesis.linguisticsummary.source.business.service.room.SampleRooms.LIVING_ROOM;
import static pl.edu.pwr.szlagor.masterthesis.linguisticsummary.source.business.service.room.SampleRooms.SLEEPING_ROOM_1;
import static pl.edu.pwr.szlagor.masterthesis.linguisticsummary.source.business.service.room.SampleRooms.TOILETTE;

import java.time.DayOfWeek;
import java.time.LocalTime;
import java.util.Arrays;
import java.util.Collections;

import pl.edu.pwr.szlagor.masterthesis.linguisticsummary.source.business.model.ActivitySchemaSourceDto;
import pl.edu.pwr.szlagor.masterthesis.linguisticsummary.source.business.model.DaySchemaSourceDto;
import pl.edu.pwr.szlagor.masterthesis.linguisticsummary.source.business.service.activity.SampleActivities;
import pl.edu.pwr.szlagor.masterthesis.linguisticsummary.source.business.service.room.SampleRooms;


/**
 * Created by Pawel on 2017-02-01.
 */
public class SampleDailies {

    public static final DaySchemaSourceDto WORKING_DAY = DaySchemaSourceDto.builder().workingDay(true).wakingHour(LocalTime.of(6, 30, 10)).dayOfWeeks(Arrays.asList(DayOfWeek.MONDAY, DayOfWeek.TUESDAY, DayOfWeek.WEDNESDAY)).activity(SampleActivities.WAKING_UP.build()).activity(SampleActivities.TOILETTE.build()).activity(SampleActivities.MEAL.build()).activity(DRESSING_UP.build()).activity(GOING_AROUND.build()).activity(SampleActivities.TOILETTE.build()).activity(SampleActivities.AT_WORK.build()).activity(DRESSING_OUT.build()).activity(SampleActivities.TOILETTE.build()).activity(DRESSING_OUT.build()).activity(SampleActivities.COOKING.build()).activity(SampleActivities.MEAL.build()).activity(SampleActivities.TOILETTE.build()).activity(SampleActivities.PLAYING_CONSOLE.build()).activity(SampleActivities.SHOPPING.build()).activity(SampleActivities.WORK_ON_DESK.build()).activity(SampleActivities.BATH.build()).sleepHour(LocalTime.of(22, 30, 10)).build();

    public static final DaySchemaSourceDto WORKING_DAY_WORK_HOME = DaySchemaSourceDto.builder().workingDay(true).wakingHour(LocalTime.of(6, 30, 10)).dayOfWeeks(Arrays.asList(DayOfWeek.MONDAY, DayOfWeek.TUESDAY, DayOfWeek.WEDNESDAY)).dayOfWeeks(Arrays.asList(DayOfWeek.TUESDAY, DayOfWeek.WEDNESDAY, DayOfWeek.THURSDAY, DayOfWeek.FRIDAY)).activity(SampleActivities.WAKING_UP.build()).activity(SampleActivities.TOILETTE.build()).activity(SampleActivities.MEAL.build()).activity(SampleActivities.MEAL.build()).activity(DRESSING_UP.build()).activity(GOING_AROUND.build()).activity(SampleActivities.TOILETTE.build()).activity(SampleActivities.AT_WORK.build()).activity(DRESSING_OUT.build()).activity(SampleActivities.TOILETTE.build()).activity(DRESSING_OUT.build()).activity(SampleActivities.COOKING.build()).activity(SampleActivities.MEAL.build()).activity(SampleActivities.TOILETTE.build()).activity(SampleActivities.WORK_ON_DESK.build()).activity(SampleActivities.WORK_ON_DESK.build()).activity(SampleActivities.READING.build()).activity(SampleActivities.BATH.build()).sleepHour(LocalTime.of(22, 30, 10)).build();

    public static final DaySchemaSourceDto WORKING_DAY_CLEANING = DaySchemaSourceDto.builder().workingDay(true).wakingHour(LocalTime.of(6, 30, 10)).dayOfWeeks(Arrays.asList(DayOfWeek.THURSDAY, DayOfWeek.FRIDAY)).activity(SampleActivities.WAKING_UP.build()).activity(SampleActivities.TOILETTE.build()).activity(SampleActivities.MEAL.build()).activity(SampleActivities.MEAL.build()).activity(DRESSING_UP.build()).activity(GOING_AROUND.build()).activity(SampleActivities.TOILETTE.build()).activity(SampleActivities.AT_WORK.build()).activity(DRESSING_OUT.build()).activity(SampleActivities.TOILETTE.build()).activity(DRESSING_OUT.build()).activity(SampleActivities.COOKING.build()).activity(SampleActivities.MEAL.build()).activity(SampleActivities.TOILETTE.build()).activity(SampleActivities.CLEANING_FLAT.build()).activity(SampleActivities.WATCHING_TV.build()).activity(SampleActivities.BATH.build()).sleepHour(LocalTime.of(22, 30, 10)).build();

    public static final DaySchemaSourceDto WORKING_DAY_OUTSIDE = DaySchemaSourceDto.builder().workingDay(true).wakingHour(LocalTime.of(6, 30, 10)).dayOfWeeks(Arrays.asList(DayOfWeek.THURSDAY, DayOfWeek.FRIDAY)).activity(SampleActivities.WAKING_UP.build()).activity(SampleActivities.TOILETTE.build()).activity(SampleActivities.MEAL.build()).activity(SampleActivities.MEAL.build()).activity(DRESSING_UP.build()).activity(GOING_AROUND.build()).activity(SampleActivities.TOILETTE.build()).activity(SampleActivities.AT_WORK.build()).activity(DRESSING_OUT.build()).activity(SampleActivities.TOILETTE.build()).activity(DRESSING_OUT.build()).activity(SampleActivities.COOKING.build()).activity(SampleActivities.MEAL.build()).activity(SampleActivities.TOILETTE.build()).activity(SampleActivities.OUT_IN_GYM.build()).activity(ActivitySchemaSourceDto.builder().averageElapsedTime(5d).locationProbability(HALL, 1.00).preferredTempInLocation(HALL, 20d).build()).activity(SampleActivities.TOILETTE.build()).activity(SampleActivities.BATH.build()).activity(SampleActivities.WATCHING_TV.build()).activity(SampleActivities.MEAL.build()).sleepHour(LocalTime.of(22, 30, 10)).build();

    public static final DaySchemaSourceDto HOME_OFFICE = DaySchemaSourceDto.builder().workingDay(true).wakingHour(LocalTime.of(6, 30, 10)).dayOfWeeks(Collections.singletonList(DayOfWeek.FRIDAY)).activity(SampleActivities.WAKING_UP.build()).activity(SampleActivities.TOILETTE.build()).activity(SampleActivities.MEAL.build()).activity(SampleActivities.MEAL.build()).activity(DRESSING_UP.build()).activity(GOING_AROUND.build()).activity(SampleActivities.TOILETTE.build()).activity(SampleActivities.WORKING_HOME.build()).activity(SampleActivities.TOILETTE.build()).activity(DRESSING_OUT.build()).activity(SampleActivities.COOKING.build()).activity(SampleActivities.MEAL.build()).activity(SampleActivities.TOILETTE.build()).activity(OUT_IN_GYM.build()).activity(ActivitySchemaSourceDto.builder().averageElapsedTime(5d).locationProbability(HALL, 1.00).preferredTempInLocation(HALL, 20d).build()).activity(SampleActivities.TOILETTE.build()).activity(SampleActivities.BATH.build()).activity(SampleActivities.WATCHING_TV.build()).activity(SampleActivities.MEAL.build()).sleepHour(LocalTime.of(22, 30, 10)).build();

    public static final DaySchemaSourceDto SATURDAY = DaySchemaSourceDto.builder().workingDay(false).wakingHour(LocalTime.of(7, 15, 00)).dayOfWeeks(Collections.singletonList(DayOfWeek.SATURDAY)).activity(SampleActivities.WAKING_UP.build()).activity(SampleActivities.TOILETTE.build()).activity(SampleActivities.MEAL.build()).activity(SampleActivities.MEAL.build()).activity(ActivitySchemaSourceDto.builder().averageElapsedTime(15d).locationProbability(SLEEPING_ROOM_1, 1.00).preferredTempInLocation(SLEEPING_ROOM_1, 22d).build()).activity(SampleActivities.TOILETTE.build()).activity(SampleActivities.SHOPPING.build()).activity(SampleActivities.DO_WASHING.build()).activity(ActivitySchemaSourceDto.builder().averageElapsedTime(10d).locationProbability(SLEEPING_ROOM_1, 1.00).preferredTempInLocation(SLEEPING_ROOM_1, 19d).build()).activity(ActivitySchemaSourceDto.builder().averageElapsedTime(10d).locationProbability(SampleRooms.SLEEPING_ROOM_2, 1.00).preferredTempInLocation(SampleRooms.SLEEPING_ROOM_2, 19d).build()).activity(ActivitySchemaSourceDto.builder().averageElapsedTime(10d).locationProbability(SampleRooms.SLEEPING_ROOM_3, 1.00).preferredTempInLocation(SampleRooms.SLEEPING_ROOM_3, 19d).build()).activity(ActivitySchemaSourceDto.builder().averageElapsedTime(20d).locationProbability(LIVING_ROOM, 1.00).preferredTempInLocation(LIVING_ROOM, 19d).build()).activity(ActivitySchemaSourceDto.builder().averageElapsedTime(5d).locationProbability(HALL, 1.00).preferredTempInLocation(HALL, 19d).build()).activity(ActivitySchemaSourceDto.builder().averageElapsedTime(20d).locationProbability(KITCHEN, 1.00).preferredTempInLocation(KITCHEN, 19d).build()).activity(ActivitySchemaSourceDto.builder().averageElapsedTime(20d).locationProbability(SampleRooms.BATHROOM, 1.00).preferredTempInLocation(SampleRooms.BATHROOM, 19d).build()).activity(ActivitySchemaSourceDto.builder().averageElapsedTime(10d).locationProbability(TOILETTE, 1.00).preferredTempInLocation(TOILETTE, 19d).build()).activity(SampleActivities.DRY_LAUNDRY.build()).activity(SampleActivities.TOILETTE.build()).activity(ActivitySchemaSourceDto.builder().averageElapsedTime(5d).locationProbability(SLEEPING_ROOM_1, 1.00).preferredTempInLocation(SLEEPING_ROOM_1, 22d).build()).activity(SampleActivities.COOKING.build()).activity(SampleActivities.MEAL.build()).activity(SampleActivities.TOILETTE.build()).activity(SampleActivities.WORK_OUT.build()).activity(SampleActivities.PLAYING_CONSOLE.build()).activity(WALK_OUT.averageElapsedTime(60d).build()).activity(SampleActivities.WATCHING_TV.build()).activity(SampleActivities.BATH.build()).sleepHour(LocalTime.of(23, 30, 00)).build();

    public static final DaySchemaSourceDto SUNDAY = DaySchemaSourceDto.builder().workingDay(false).wakingHour(LocalTime.of(7, 15, 00)).dayOfWeeks(Collections.singletonList(DayOfWeek.SUNDAY)).activity(SampleActivities.WAKING_UP.build()).activity(SampleActivities.TOILETTE.build()).activity(SampleActivities.MEAL.build()).activity(SampleActivities.MEAL.build()).activity(ActivitySchemaSourceDto.builder().averageElapsedTime(15d).locationProbability(SLEEPING_ROOM_1, 1.00).preferredTempInLocation(SLEEPING_ROOM_1, 22d).build()).activity(SampleActivities.TOILETTE.build()).activity(SampleActivities.SHOPPING.build()).activity(ActivitySchemaSourceDto.builder().averageElapsedTime(20d).locationProbability(LIVING_ROOM, 1.00).preferredTempInLocation(LIVING_ROOM, 19d).build()).activity(ActivitySchemaSourceDto.builder().averageElapsedTime(5d).locationProbability(HALL, 1.00).preferredTempInLocation(HALL, 19d).build()).activity(ActivitySchemaSourceDto.builder().averageElapsedTime(20d).locationProbability(KITCHEN, 1.00).preferredTempInLocation(KITCHEN, 19d).build()).activity(SampleActivities.WATCHING_TV.build()).activity(SampleActivities.WALK_OUT.build()).activity(ActivitySchemaSourceDto.builder().averageElapsedTime(5d).locationProbability(HALL, 1.00).preferredTempInLocation(HALL, 19d).build()).activity(SampleActivities.TOILETTE.build()).activity(ActivitySchemaSourceDto.builder().averageElapsedTime(5d).locationProbability(SLEEPING_ROOM_1, 1.00).preferredTempInLocation(SLEEPING_ROOM_1, 22d).build()).activity(SampleActivities.COOKING.build()).activity(SampleActivities.MEAL.build()).activity(SampleActivities.TOILETTE.build()).activity(SampleActivities.PLAYING_CONSOLE.build()).activity(SampleActivities.WATCHING_TV.build()).activity(SampleActivities.BATH.build()).sleepHour(LocalTime.of(23, 30, 00)).build();


}
