package pl.edu.pwr.szlagor.masterthesis.linguisticsummary.source.business.service.daySchema;

import static pl.edu.pwr.szlagor.masterthesis.linguisticsummary.source.business.service.room.SampleRooms.HALL;
import static pl.edu.pwr.szlagor.masterthesis.linguisticsummary.source.business.service.room.SampleRooms.KITCHEN;
import static pl.edu.pwr.szlagor.masterthesis.linguisticsummary.source.business.service.room.SampleRooms.LIVING_ROOM;
import static pl.edu.pwr.szlagor.masterthesis.linguisticsummary.source.business.service.room.SampleRooms.SLEEPING_ROOM_1;
import static pl.edu.pwr.szlagor.masterthesis.linguisticsummary.source.business.service.room.SampleRooms.TOILETTE;

import java.time.DayOfWeek;
import java.time.LocalTime;
import java.util.Arrays;
import java.util.Collections;

import pl.edu.pwr.szlagor.masterthesis.linguisticsummary.episodic.model.enums.MediaType;
import pl.edu.pwr.szlagor.masterthesis.linguisticsummary.source.business.model.ActivitySchemaSourceDto;
import pl.edu.pwr.szlagor.masterthesis.linguisticsummary.source.business.model.DaySchemaSourceDto;
import pl.edu.pwr.szlagor.masterthesis.linguisticsummary.source.business.model.MediaUsageSourceDto;
import pl.edu.pwr.szlagor.masterthesis.linguisticsummary.source.business.service.activity.SampleActivities;
import pl.edu.pwr.szlagor.masterthesis.linguisticsummary.source.business.service.device.SampleDevices;
import pl.edu.pwr.szlagor.masterthesis.linguisticsummary.source.business.service.room.SampleRooms;


/**
 * Created by Pawel on 2017-02-01.
 */
public class SampleDailies {

    public static final DaySchemaSourceDto WORKING_DAY = DaySchemaSourceDto.builder().workingDay(true).wakingHour(LocalTime.of(6, 30, 10)).dayOfWeeks(Arrays.asList(DayOfWeek.MONDAY, DayOfWeek.TUESDAY, DayOfWeek.WEDNESDAY)).activity(SampleActivities.WAKING_UP.build()).activity(SampleActivities.TOILETTE.build()).activity(SampleActivities.MEAL.build()).activity(ActivitySchemaSourceDto.builder().name("dressing up").averageElapsedTime(10d).locationProbability(SLEEPING_ROOM_1, 1.00).preferredTempInLocation(SLEEPING_ROOM_1, 22d).build()).activity(ActivitySchemaSourceDto.builder().name("going through").averageElapsedTime(5d).locationProbability(HALL, 1.00).preferredTempInLocation(HALL, 20d).build()).activity(SampleActivities.TOILETTE.build()).activity(SampleActivities.AT_WORK.build()).activity(ActivitySchemaSourceDto.builder().name("dressing out").averageElapsedTime(5d).locationProbability(HALL, 1.00).preferredTempInLocation(HALL, 20d).build()).activity(SampleActivities.TOILETTE.build()).activity(ActivitySchemaSourceDto.builder().name("dressing to casual clothes").averageElapsedTime(10d).locationProbability(SLEEPING_ROOM_1, 1.00).preferredTempInLocation(SLEEPING_ROOM_1, 22d).build()).activity(SampleActivities.COOKING.build()).activity(SampleActivities.MEAL.build()).activity(SampleActivities.TOILETTE.build()).activity(SampleActivities.PLAYING_CONSOLE.build()).activity(SampleActivities.SHOPPING.build()).activity(SampleActivities.WORK_ON_DESK.build()).activity(SampleActivities.BATH.build()).sleepHour(LocalTime.of(22, 30, 10)).build();

    public static final DaySchemaSourceDto WORKING_DAY_WORK_HOME = DaySchemaSourceDto.builder().workingDay(true).wakingHour(LocalTime.of(6, 30, 10)).dayOfWeeks(Arrays.asList(DayOfWeek.MONDAY, DayOfWeek.TUESDAY, DayOfWeek.WEDNESDAY)).dayOfWeeks(Arrays.asList(DayOfWeek.TUESDAY, DayOfWeek.WEDNESDAY, DayOfWeek.THURSDAY, DayOfWeek.FRIDAY)).activity(SampleActivities.WAKING_UP.build()).activity(SampleActivities.TOILETTE.build()).activity(SampleActivities.MEAL.build()).activity(SampleActivities.MEAL.build()).activity(ActivitySchemaSourceDto.builder().name("dressing up").averageElapsedTime(10d).locationProbability(SLEEPING_ROOM_1, 1.00).preferredTempInLocation(SLEEPING_ROOM_1, 22d).build()).activity(ActivitySchemaSourceDto.builder().name("going through").averageElapsedTime(5d).locationProbability(HALL, 1.00).preferredTempInLocation(HALL, 20d).build()).activity(SampleActivities.TOILETTE.build()).activity(SampleActivities.AT_WORK.build()).activity(ActivitySchemaSourceDto.builder().name("dressing out").averageElapsedTime(5d).locationProbability(HALL, 1.00).preferredTempInLocation(HALL, 20d).build()).activity(SampleActivities.TOILETTE.build()).activity(ActivitySchemaSourceDto.builder().name("dressing to casual clothes").averageElapsedTime(10d).locationProbability(SLEEPING_ROOM_1, 1.00).preferredTempInLocation(SLEEPING_ROOM_1, 22d).build()).activity(SampleActivities.COOKING.build()).activity(SampleActivities.MEAL.build()).activity(SampleActivities.TOILETTE.build()).activity(SampleActivities.WORK_ON_DESK.build()).activity(SampleActivities.WORK_ON_DESK.build()).activity(SampleActivities.READING.build()).activity(SampleActivities.BATH.build()).sleepHour(LocalTime.of(22, 30, 10)).build();

    public static final DaySchemaSourceDto WORKING_DAY_CLEANING = DaySchemaSourceDto.builder().workingDay(true).wakingHour(LocalTime.of(6, 30, 10)).dayOfWeeks(Arrays.asList(DayOfWeek.THURSDAY, DayOfWeek.FRIDAY)).activity(SampleActivities.WAKING_UP.build()).activity(SampleActivities.TOILETTE.build()).activity(SampleActivities.MEAL.build()).activity(SampleActivities.MEAL.build()).activity(ActivitySchemaSourceDto.builder().name("dressing up").averageElapsedTime(10d).locationProbability(SLEEPING_ROOM_1, 1.00).preferredTempInLocation(SLEEPING_ROOM_1, 22d).build()).activity(ActivitySchemaSourceDto.builder().name("going through").averageElapsedTime(5d).locationProbability(HALL, 1.00).preferredTempInLocation(HALL, 20d).build()).activity(SampleActivities.TOILETTE.build()).activity(SampleActivities.AT_WORK.build()).activity(ActivitySchemaSourceDto.builder().name("dressing out").averageElapsedTime(5d).locationProbability(HALL, 1.00).preferredTempInLocation(HALL, 20d).build()).activity(SampleActivities.TOILETTE.build()).activity(ActivitySchemaSourceDto.builder().name("dressing to casual clothes").averageElapsedTime(10d).locationProbability(SLEEPING_ROOM_1, 1.00).preferredTempInLocation(SLEEPING_ROOM_1, 22d).build()).activity(SampleActivities.COOKING.build()).activity(SampleActivities.MEAL.build()).activity(SampleActivities.TOILETTE.build()).activity(ActivitySchemaSourceDto.builder().name("cleaning flat").averageElapsedTime(80d).locationProbability(SLEEPING_ROOM_1, 0.2).locationProbability(LIVING_ROOM, 0.2).locationProbability(TOILETTE, 0.1).locationProbability(KITCHEN, 0.2).locationProbability(SampleRooms.SLEEPING_ROOM_2, 0.1).locationProbability(HALL, 0.2).preferredTempInLocation(SLEEPING_ROOM_1, 18d).preferredTempInLocation(LIVING_ROOM, 18d).preferredTempInLocation(TOILETTE, 18d).preferredTempInLocation(KITCHEN, 18d).preferredTempInLocation(SampleRooms.SLEEPING_ROOM_2, 18d).preferredTempInLocation(HALL, 18d).mediaUsageSourceDto(MediaUsageSourceDto.builder().mediaType(MediaType.ELECTRICITY).location(SLEEPING_ROOM_1).usagePerMinute(2).build()).mediaUsageSourceDto(MediaUsageSourceDto.builder().mediaType(MediaType.ELECTRICITY).location(LIVING_ROOM).usagePerMinute(2).build()).mediaUsageSourceDto(MediaUsageSourceDto.builder().mediaType(MediaType.ELECTRICITY).location(TOILETTE).usagePerMinute(2).build()).mediaUsageSourceDto(MediaUsageSourceDto.builder().mediaType(MediaType.COLD_WATER).location(TOILETTE).usagePerMinute(3).build()).mediaUsageSourceDto(MediaUsageSourceDto.builder().mediaType(MediaType.ELECTRICITY).location(KITCHEN).usagePerMinute(2).build()).mediaUsageSourceDto(MediaUsageSourceDto.builder().mediaType(MediaType.COLD_WATER).location(KITCHEN).usagePerMinute(3).build()).mediaUsageSourceDto(MediaUsageSourceDto.builder().mediaType(MediaType.ELECTRICITY).location(HALL).usagePerMinute(2).build()).build()).activity(SampleActivities.WATCHING_TV.build()).activity(SampleActivities.BATH.build()).sleepHour(LocalTime.of(22, 30, 10)).build();

    public static final DaySchemaSourceDto WORKING_DAY_OUTSIDE = DaySchemaSourceDto.builder().workingDay(true).wakingHour(LocalTime.of(6, 30, 10)).dayOfWeeks(Arrays.asList(DayOfWeek.THURSDAY, DayOfWeek.FRIDAY)).activity(SampleActivities.WAKING_UP.build()).activity(SampleActivities.TOILETTE.build()).activity(SampleActivities.MEAL.build()).activity(SampleActivities.MEAL.build()).activity(ActivitySchemaSourceDto.builder().name("dressing up").averageElapsedTime(10d).locationProbability(SLEEPING_ROOM_1, 1.00).preferredTempInLocation(SLEEPING_ROOM_1, 22d).build()).activity(ActivitySchemaSourceDto.builder().name("going through").averageElapsedTime(5d).locationProbability(HALL, 1.00).preferredTempInLocation(HALL, 20d).build()).activity(SampleActivities.TOILETTE.build()).activity(SampleActivities.AT_WORK.build()).activity(ActivitySchemaSourceDto.builder().name("dressing out").averageElapsedTime(5d).locationProbability(HALL, 1.00).preferredTempInLocation(HALL, 20d).build()).activity(SampleActivities.TOILETTE.build()).activity(ActivitySchemaSourceDto.builder().name("dressing to casual clothes").averageElapsedTime(10d).locationProbability(SLEEPING_ROOM_1, 1.00).preferredTempInLocation(SLEEPING_ROOM_1, 22d).build()).activity(SampleActivities.COOKING.build()).activity(SampleActivities.MEAL.build()).activity(SampleActivities.TOILETTE.build()).activity(ActivitySchemaSourceDto.builder().averageElapsedTime(120d).name("out - in gym").build()).activity(ActivitySchemaSourceDto.builder().averageElapsedTime(5d).locationProbability(HALL, 1.00).preferredTempInLocation(HALL, 20d).build()).activity(SampleActivities.TOILETTE.build()).activity(SampleActivities.BATH.build()).activity(SampleActivities.WATCHING_TV.build()).activity(SampleActivities.MEAL.build()).sleepHour(LocalTime.of(22, 30, 10)).build();

    public static final DaySchemaSourceDto HOME_OFFICE = DaySchemaSourceDto.builder().workingDay(true).wakingHour(LocalTime.of(6, 30, 10)).dayOfWeeks(Collections.singletonList(DayOfWeek.FRIDAY)).activity(SampleActivities.WAKING_UP.build()).activity(SampleActivities.TOILETTE.build()).activity(SampleActivities.MEAL.build()).activity(SampleActivities.MEAL.build()).activity(ActivitySchemaSourceDto.builder().name("dressing up").averageElapsedTime(10d).locationProbability(SLEEPING_ROOM_1, 1.00).preferredTempInLocation(SLEEPING_ROOM_1, 22d).build()).activity(ActivitySchemaSourceDto.builder().averageElapsedTime(5d).locationProbability(HALL, 1.00).name("going through").preferredTempInLocation(HALL, 20d).build()).activity(SampleActivities.TOILETTE.build()).activity(ActivitySchemaSourceDto.builder().name("working").averageElapsedTime(120d).locationProbability(SLEEPING_ROOM_1, 1.00).preferredTempInLocation(SLEEPING_ROOM_1, 22d).timeOfDeviceUsage(SampleDevices.PC, 1.0).mediaUsageSourceDto(MediaUsageSourceDto.builder().mediaType(MediaType.ELECTRICITY).usagePerMinute(5.0).location(SLEEPING_ROOM_1).build()).build()).activity(ActivitySchemaSourceDto.builder().name("working").averageElapsedTime(120d).locationProbability(LIVING_ROOM, 1.00).preferredTempInLocation(SLEEPING_ROOM_1, 22d).timeOfDeviceUsage(SampleDevices.LAPTOP, 1.0).mediaUsageSourceDto(MediaUsageSourceDto.builder().mediaType(MediaType.ELECTRICITY).usagePerMinute(5.0).location(SLEEPING_ROOM_1).build()).preferredTempInLocation(LIVING_ROOM, 22d).build()).activity(ActivitySchemaSourceDto.builder().name("pause in working").averageElapsedTime(30d).locationProbability(KITCHEN, 1.00).preferredTempInLocation(KITCHEN, 22d).build()).activity(ActivitySchemaSourceDto.builder().name("working").averageElapsedTime(210d).locationProbability(SLEEPING_ROOM_1, 1.00).preferredTempInLocation(SLEEPING_ROOM_1, 22d).timeOfDeviceUsage(SampleDevices.LAPTOP, 1.0).mediaUsageSourceDto(MediaUsageSourceDto.builder().mediaType(MediaType.ELECTRICITY).usagePerMinute(5.0).location(SLEEPING_ROOM_1).build()).preferredTempInLocation(SLEEPING_ROOM_1, 22d).build()).activity(SampleActivities.TOILETTE.build()).activity(ActivitySchemaSourceDto.builder().name("dressing to casual clothes").averageElapsedTime(10d).locationProbability(SLEEPING_ROOM_1, 1.00).preferredTempInLocation(SLEEPING_ROOM_1, 22d).build()).activity(SampleActivities.COOKING.build()).activity(SampleActivities.MEAL.build()).activity(SampleActivities.TOILETTE.build()).activity(ActivitySchemaSourceDto.builder().averageElapsedTime(120d).name("out - in gym").build()).activity(ActivitySchemaSourceDto.builder().averageElapsedTime(5d).locationProbability(HALL, 1.00).preferredTempInLocation(HALL, 20d).build()).activity(SampleActivities.TOILETTE.build()).activity(SampleActivities.BATH.build()).activity(SampleActivities.WATCHING_TV.build()).activity(SampleActivities.MEAL.build()).sleepHour(LocalTime.of(22, 30, 10)).build();

    public static final DaySchemaSourceDto SATURDAY = DaySchemaSourceDto.builder().workingDay(false).wakingHour(LocalTime.of(7, 15, 00)).dayOfWeeks(Collections.singletonList(DayOfWeek.SATURDAY)).activity(SampleActivities.WAKING_UP.build()).activity(SampleActivities.TOILETTE.build()).activity(SampleActivities.MEAL.build()).activity(SampleActivities.MEAL.build()).activity(ActivitySchemaSourceDto.builder().averageElapsedTime(15d).locationProbability(SLEEPING_ROOM_1, 1.00).preferredTempInLocation(SLEEPING_ROOM_1, 22d).build()).activity(SampleActivities.TOILETTE.build()).activity(SampleActivities.SHOPPING.build()).activity(SampleActivities.DO_WASHING.build()).activity(ActivitySchemaSourceDto.builder().averageElapsedTime(10d).locationProbability(SLEEPING_ROOM_1, 1.00).preferredTempInLocation(SLEEPING_ROOM_1, 19d).build()).activity(ActivitySchemaSourceDto.builder().averageElapsedTime(10d).locationProbability(SampleRooms.SLEEPING_ROOM_2, 1.00).preferredTempInLocation(SampleRooms.SLEEPING_ROOM_2, 19d).build()).activity(ActivitySchemaSourceDto.builder().averageElapsedTime(10d).locationProbability(SampleRooms.SLEEPING_ROOM_3, 1.00).preferredTempInLocation(SampleRooms.SLEEPING_ROOM_3, 19d).build()).activity(ActivitySchemaSourceDto.builder().averageElapsedTime(20d).locationProbability(LIVING_ROOM, 1.00).preferredTempInLocation(LIVING_ROOM, 19d).build()).activity(ActivitySchemaSourceDto.builder().averageElapsedTime(5d).locationProbability(HALL, 1.00).preferredTempInLocation(HALL, 19d).build()).activity(ActivitySchemaSourceDto.builder().averageElapsedTime(20d).locationProbability(KITCHEN, 1.00).preferredTempInLocation(KITCHEN, 19d).build()).activity(ActivitySchemaSourceDto.builder().averageElapsedTime(20d).locationProbability(SampleRooms.BATHROOM, 1.00).preferredTempInLocation(SampleRooms.BATHROOM, 19d).build()).activity(ActivitySchemaSourceDto.builder().averageElapsedTime(10d).locationProbability(TOILETTE, 1.00).preferredTempInLocation(TOILETTE, 19d).build()).activity(SampleActivities.DRY_LAUNDRY.build()).activity(SampleActivities.TOILETTE.build()).activity(ActivitySchemaSourceDto.builder().averageElapsedTime(5d).locationProbability(SLEEPING_ROOM_1, 1.00).preferredTempInLocation(SLEEPING_ROOM_1, 22d).build()).activity(SampleActivities.COOKING.build()).activity(SampleActivities.MEAL.build()).activity(SampleActivities.TOILETTE.build()).activity(SampleActivities.WORK_OUT.build()).activity(SampleActivities.PLAYING_CONSOLE.build()).activity(ActivitySchemaSourceDto.builder().averageElapsedTime(60d).name("walking out").build()).activity(SampleActivities.WATCHING_TV.build()).activity(SampleActivities.BATH.build()).sleepHour(LocalTime.of(23, 30, 00)).build();

    public static final DaySchemaSourceDto SUNDAY = DaySchemaSourceDto.builder().workingDay(false).wakingHour(LocalTime.of(7, 15, 00)).dayOfWeeks(Collections.singletonList(DayOfWeek.SUNDAY)).activity(SampleActivities.WAKING_UP.build()).activity(SampleActivities.TOILETTE.build()).activity(SampleActivities.MEAL.build()).activity(SampleActivities.MEAL.build()).activity(ActivitySchemaSourceDto.builder().averageElapsedTime(15d).locationProbability(SLEEPING_ROOM_1, 1.00).preferredTempInLocation(SLEEPING_ROOM_1, 22d).build()).activity(SampleActivities.TOILETTE.build()).activity(SampleActivities.SHOPPING.build()).activity(ActivitySchemaSourceDto.builder().averageElapsedTime(20d).locationProbability(LIVING_ROOM, 1.00).preferredTempInLocation(LIVING_ROOM, 19d).build()).activity(ActivitySchemaSourceDto.builder().averageElapsedTime(5d).locationProbability(HALL, 1.00).preferredTempInLocation(HALL, 19d).build()).activity(ActivitySchemaSourceDto.builder().averageElapsedTime(20d).locationProbability(KITCHEN, 1.00).preferredTempInLocation(KITCHEN, 19d).build()).activity(SampleActivities.WATCHING_TV.build()).activity(ActivitySchemaSourceDto.builder().averageElapsedTime(120d).name("out - walk").build()).activity(ActivitySchemaSourceDto.builder().averageElapsedTime(5d).locationProbability(HALL, 1.00).preferredTempInLocation(HALL, 19d).build()).activity(SampleActivities.TOILETTE.build()).activity(ActivitySchemaSourceDto.builder().averageElapsedTime(5d).locationProbability(SLEEPING_ROOM_1, 1.00).preferredTempInLocation(SLEEPING_ROOM_1, 22d).build()).activity(SampleActivities.COOKING.build()).activity(SampleActivities.MEAL.build()).activity(SampleActivities.TOILETTE.build()).activity(SampleActivities.PLAYING_CONSOLE.build()).activity(SampleActivities.WATCHING_TV.build()).activity(SampleActivities.BATH.build()).sleepHour(LocalTime.of(23, 30, 00)).build();


}
